format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$nix_shell\
$cmd_duration\
$line_break\
$character
"""

[nix_shell]
disabled = false
symbol = ""
format = "[nix:\\($state\\)]($style) "

[git_branch]
symbol = ""
format = "[git:\\($branch\\)]($style) "

[python]
symbol = ""
format = "[venv:\\($virtualenv\\)]($style) "
detect_extensions = []
detect_files = []
detect_folders = []
